import { MatchState } from '../../../utils';

export const sampleData = [
  {
    id: 1,
    name: '',
    nextMatchId: 84,
    tournamentRoundText: '1',
    startTime: '',
    state: MatchState.WalkOver,
    participants: [
      {
        id: '9397971f-4b2f-44eb-a094-722eb286c59b',
        resultText: null,
        isWinner: true,
        status: null,
        name: 'Zane Attard',
        club: 'Prodigy',
      },
    ],
  },
  {
    id: 81,
    name: 'B081',
    nextMatchId: 84,
    tournamentRoundText: '1',
    startTime: '2:00pm',
    state: MatchState.ScoreDone,
    participants: [
      {
        id: 'B081a',
        resultText: null,
        isWinner: false,
        status: null,
        name: 'Lachlan MacGowan',
        club: 'Taya Taekwondo',
      },
      {
        id: 'B081b',
        resultText: null,
        isWinner: true,
        status: null,
        name: 'Brock Smith',
        club: 'MAS',
      },
    ],
  },
  {
    id: 82,
    name: 'B082',
    nextMatchId: 85,
    tournamentRoundText: '1',
    startTime: '2:15pm',
    state: MatchState.ScoreDone,
    participants: [
      {
        id: 'B082a',
        resultText: null,
        isWinner: false,
        status: null,
        name: 'Ethan Khuu',
        club: 'Irontiger Taekwondo',
      },
      {
        id: 'B082b',
        resultText: null,
        isWinner: true,
        status: null,
        name: 'Ethan Banaghan',
        club: 'St George Martial Arts',
      },
    ],
  },
  {
    id: 83,
    name: 'B083',
    nextMatchId: 85,
    tournamentRoundText: '1',
    startTime: '2:30pm',
    state: MatchState.ScoreDone,
    participants: [
      {
        id: 'B083a',
        resultText: null,
        isWinner: false,
        status: null,
        name: 'Daniel Kassis',
        club: 'Red Dragon',
      },
      {
        id: 'B083b',
        resultText: null,
        isWinner: true,
        status: null,
        name: 'Joshua Harb',
        club: 'Prodigy',
      },
    ],
  },
  {
    id: 84,
    name: 'B084',
    nextMatchId: 86,
    tournamentRoundText: '1',
    startTime: '3:00pm',
    state: MatchState.ScoreDone,
    participants: [
      {
        id: 'B084a',
        resultText: null,
        isWinner: false,
        status: null,
        name: 'Zane Attard',
        club: 'Prodigy',
      },
      {
        id: 'B084b',
        resultText: null,
        isWinner: true,
        status: null,
        name: 'Brock Smith',
        club: 'MAS',
      },
    ],
  },
  {
    id: 85,
    name: 'B085',
    nextMatchId: 86,
    tournamentRoundText: '1',
    startTime: '3:15pm',
    state: MatchState.ScoreDone,
    participants: [
      {
        id: 'B085a',
        resultText: null,
        isWinner: false,
        status: null,
        name: 'Ethan Banaghan',
        club: 'St George Martial Arts',
      },
      {
        id: 'B085b',
        resultText: null,
        isWinner: true,
        status: null,
        name: 'Joshua Harb',
        club: 'Prodigy',
      },
    ],
  },
  {
    id: 86,
    name: 'B086',
    nextMatchId: null,
    tournamentRoundText: '1',
    startTime: '4:00pm',
    state: MatchState.ScoreDone,
    participants: [
      {
        id: 'B086a',
        resultText: null,
        isWinner: false,
        status: null,
        name: 'Brock Smith',
        club: 'MAS',
      },
      {
        id: 'B086b',
        resultText: null,
        isWinner: true,
        status: null,
        name: 'Joshua Harb',
        club: 'Prodigy',
      },
    ],
  },
];
